
name: Action

on:
  workflow_dispatch:
  schedule:
    - cron: 20 5 * * *


jobs:
    build:
      runs-on: ubuntu-20.04

      steps:
        - name: 更改交换空间并link构建空间
          uses: zhlhlf/maximize-build-space@master
          with:
            swap-size-mb: 8192
            
        - name: 获取本仓库源码
          uses: actions/checkout@main
          
        - uses: actions/checkout@main
        - name: Setup Node.js environment
          uses: actions/setup-node@main
          with:
            node-version: 18
            
        - name: 操作
          run: |  
              export tyys="${{ secrets.tyys }}"
              export tyy_family_id="${{ secrets.tyy_family_id }}"
              export TELEGRAM_CHAT_ID="${{ secrets.TELEGRAM_CHAT_ID }}"
              export TELEGRAM_BOT_TOKEN="${{ secrets.TELEGRAM_BOT_TOKEN }}"
              export WX_PUSHER_APP_TOKEN="${{ secrets.WX_PUSHER_APP_TOKEN }}"
              export WX_PUSHER_UID="${{ secrets.WX_PUSHER_UID }}"
              
              npm install >/dev/null 2>&1
              npm start
              
